//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDIWT_MS_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDIWT_MS_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cell Library (*.cell) | *.cel|Dgn File(*.dng) | *.dgn|All Files (*.*) | *.* 的本地化字符串。
        /// </summary>
        internal static string CellLibraryFilter {
            get {
                return ResourceManager.GetString("CellLibraryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel 2007-2017文件(*.xlsx)|*.xlsx 的本地化字符串。
        /// </summary>
        internal static string ExcelFilter {
            get {
                return ResourceManager.GetString("ExcelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示： 的本地化字符串。
        /// </summary>
        internal static string PromptHeader {
            get {
                return ResourceManager.GetString("PromptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要放置的四边平面(或右键退出) 的本地化字符串。
        /// </summary>
        internal static string PutArmorToolChoosePlan {
            get {
                return ResourceManager.GetString("PutArmorToolChoosePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认放置 的本地化字符串。
        /// </summary>
        internal static string PutArmorToolConfirm {
            get {
                return ResourceManager.GetString("PutArmorToolConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按平面放置单元 的本地化字符串。
        /// </summary>
        internal static string PutArmorToolName {
            get {
                return ResourceManager.GetString("PutArmorToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选元素类型不是&lt;Shape&gt; 的本地化字符串。
        /// </summary>
        internal static string PutArmorToolRejectReason {
            get {
                return ResourceManager.GetString("PutArmorToolRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选Shape不是平面Shape 的本地化字符串。
        /// </summary>
        internal static string PutArmorToolRejectReason2 {
            get {
                return ResourceManager.GetString("PutArmorToolRejectReason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选平面shape不是矩形 的本地化字符串。
        /// </summary>
        internal static string PutArmorToolRejectReason3 {
            get {
                return ResourceManager.GetString("PutArmorToolRejectReason3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态： 的本地化字符串。
        /// </summary>
        internal static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string SuccessString {
            get {
                return ResourceManager.GetString("SuccessString", resourceCulture);
            }
        }
    }
}
